### ISSUE TITLE
Background bot run?

### ISSUE THREAD

**Issue by vlad1371** [aeon0/botty#103]
Hi there,

First al all let me tell you that I love you 100% for what you're doing regarding the bot, you make me feel like a child again. Back in the days i was level 99 on a Gamespace server doing only baal runs with my friends.
My kindly question for you, can you please think of a way to somehow minimize the bot or let it run in the background leting you use the pc? For me this is the biggest problem and i tried to sort it out with a vm but failed. 

Really wait for your feedback

Thanks,
Vlad

**Comment by aeon0** [comment]
Hi, this will only work with vms or cloud computing. Please move your questions to the discord channel as github issues are used for bugs only (as you already did).
