### ISSUE TITLE
Alt not being pressed and no item picked in 0.4.0

### ISSUE THREAD

**Issue by Devilbilly** [aeon0/botty#111]
**Botty Version**
What version of botty are you running? Are you using a pre-compiled release? Which one. Are you using the latest master branch? On which commit?
Release build v0.4.0
**Describe the bug**
Alt not being pressed, no item nor pots are picked
**To Reproduce**
3. etc.

**Expected behavior**
Should press alt and pick items
**Screenshots / Video**
If applicable, add screenshots or even better a short video of the error happening to help explain your problem. Botty often automatically makes screenshots when something goes wrong. Add these also.
![image](https://user-images.githubusercontent.com/5964526/143350749-3b48ade2-c92f-4cd7-9a4e-ece7cc812cc6.png)
The snapshot is taken by loot_screenshots=1. As you can see there's pots on the ground and the bot can't see it (since no alt pressed) nor pick it up.
**Logs**
Add the relevant part of the info.log in this section. Either upload it as a fail or copy-paste the relevant part in here.
[2021-11-25 09:28:28,778] INFO       Setting up Sorceress
[2021-11-25 09:28:28,807] INFO       Starting game #1
[2021-11-25 09:28:28,886] WARNING    You are creating a game in online mode!
[2021-11-25 09:28:48,944] INFO       Run Pindle
**Additional info**
Add any other information about the problem here.
1. I have turned on loot_screenshots=1 and it doesn't show any items in snapshot.
2. v0.3.0 works well but not v0.4.0
3. changing hotkey won't help

Thanks,
DB

**Comment by mgleed** [comment]
Hey, run F9 again for 4.0 and let us know if this resolves your issue.

**Comment by Devilbilly** [comment]
Hi,

F9 solved the issue.

Thanks. 

Btw, F9 would set my d2 to window mode...

**Comment by aeon0** [comment]
> Btw, F9 would set my d2 to window mode...

100% intended. Change offset to 0 and/or res param if you don't like it.
