### ISSUE TITLE
Template not matching for full rejuvs?

### ISSUE THREAD

**Issue by mgleed** [aeon0/botty#112]
**Botty Version**
Master branch commit `11b55a1` (post 4.0). 1920x1080. Belt rows =4. HP=2, RV=2.

**Describe the bug**
Bot won't pick up full_rejuv potions when plain rejuv potion is disabled in params.ini and full_rejuv is enabled. Bot starts picking up both when plain rejuv is re-enabled (log file reads match for regular rejuv).

**To Reproduce**
Make sure you need rejuv potions, then watch bot during pickit when plain rejuv potion is disabled in params.ini. Might only happen in 1920x1080, haven't tested 720p

**Screenshots / Video**
```
;potions
misc_rejuvenation_potion=0
misc_full_rejuvenation_potion=1
misc_super_healing_potion=1
misc_super_mana_potion=1
```
**video**
https://user-images.githubusercontent.com/9866239/143371894-086cbef6-6f28-42d3-b1bc-8c9418573484.mp4

![Screenshot 2021-11-24 213251](https://user-images.githubusercontent.com/9866239/143371927-74721175-10da-4026-863c-06ce88b4ebcb.png)
```
;potions
misc_rejuvenation_potion=1
misc_full_rejuvenation_potion=1
misc_super_healing_potion=1
misc_super_mana_potion=1
```

**video**
https://user-images.githubusercontent.com/9866239/143371975-6a4f0076-2fd0-4830-abe6-1ca85a4b7ee8.mp4

![misc_rejuv](https://user-images.githubusercontent.com/9866239/143371993-54d27d7b-ecf4-4db3-ac7c-4159fe758ac4.png)

Graphics debugger:
![debug](https://user-images.githubusercontent.com/9866239/143373009-25562699-ecfe-407e-903e-72b9cede0522.png)

I looked at the 1920x1080 assets and they seem fine. Regular rejuv and full rejuv are equivalent pixels/in so should be appropriate for 1920.

**Comment by aeon0** [comment]
Without looking into it think see the problem, and we might have that in all situations where there is a item that is a "subset" of another. e.g. 
What happens is, both are matched, but normal rejuv is slightly higher, so bitty decides it is this item and discards the other one.
We might have similar issues with superior stuff :/

**Comment by mgleed** [comment]
Maybe loading template files in order from longest to shortest filename. Then maybe a way to check if a template name is a substring of an already loaded template. Tbh not super familiar with that part of src

**Comment by mgleed** [comment]
@aeon0 Still persists for me in 1080p, but I don't observe this issue in 720p, at least in graphics debug mode it detects the full rv pot and ignores the normal rv pot, haven't tried it live. I also tried colossus voulge=0 and superior colossus voulge=1 in 1080p and the sup CV detected fine. I'm suspecting maybe a template issue? I'll play around and see if I can figure out the solution.
