### ISSUE TITLE
Stop health monitoring while still in map looking for tp

### ISSUE THREAD

**Issue by jagarop** [aeon0/botty#144]
Will edit with better info later, its a known issue by @aeon0 

**Describe the bug**
Botty is not looking for your health when its trying to tp so if it gets stuck in the loop trying to find the Tp it made but its under attack then it won't chicken or or heal or anything.

**Comment by aeon0** [comment]
No need to add more info. As stated, it's know issue, it's known how to fix it, it is just quite a bit of refactoring to be done. We keep this open to track it.
