### ISSUE TITLE
Feature Request : use directinput to avoid detection 

### ISSUE THREAD

**Issue by franklin050187** [aeon0/botty#150]
Hello,

Would it be better to use directinput to avoid detection in case our friend decide to ban offline botting ?

Source : 
https://stackoverflow.com/questions/14489013/simulate-python-keypresses-for-controlling-a-game
http://www.gamespp.com/directx/directInputKeyboardScanCodes.html
https://pythonprogramming.net/direct-input-game-python-plays-gta-v/?completed=/open-cv-basics-python-plays-gta-v/

**Comment by aeon0** [comment]
It does not matter, all of the above is detectable just as easily.
There are two options you have if you are worried about this:
1) Write your own Keyboard and Mouse driver
2) Emulate the hardware e.g. via a arduino board
