### ISSUE TITLE
Need a3 mission for run 3c.

### ISSUE THREAD

**Issue by amberblade** [aeon0/botty#157]
Need k3c bot. Is it in your TODO list.

**Comment by aeon0** [comment]
Hi, I am not really sure what this is. Questions will be answered on the Discrod (https://discord.gg/Jf3J8cuXWg). We try to keep github issues for bug reports only, thx.

**Comment by nekolr** [comment]
> Hi, I am not really sure what this is. Questions will be answered on the Discrod (https://discord.gg/Jf3J8cuXWg). We try to keep github issues for bug reports only, thx.

that's travincal's senator
