### ISSUE TITLE
How to set hotkey of sorceress. 

### ISSUE THREAD

**Issue by EthanJian** [aeon0/botty#168]
I don't understand how you set hotkey[skill] in your code.

Could you share the default setting of hotkey[skill] of sorceress?

it might be like below:
[hotkey] = [skill & TP]
F1 = teleport
F2 = ?
F3 = ?
F4 = ?
?  = TP roll

or could you share how you set those hotkey[skill]?

Thanks.

**Comment by EthanJian** [comment]
=.=    I found it, it is in the "params.ini".

**Comment by EthanJian** [comment]
I'm trying to perform "python src/run.py".
Yet, where is the params.ini by "src/run.py" loaded?
I can not see the params.ini in the folder of src.

**Comment by EthanJian** [comment]
OMG!   Botty sold my src torch just now.  T^T 

Where could I change the selling range of item space in your code when pack full ?

There are space of 36 lattices in the pack. 

How can I only sell the left half part (18 lattices)?  Do not touch right half part!!!!!

**Comment by aeon0** [comment]
There is a Discord channel which can asnwer all of these questions: https://discord.gg/Jf3J8cuXWg

Github is for bug reports only, thx.
