### ISSUE TITLE
(botty v0.4.3) show_items doesn't seem to work?

### ISSUE THREAD

**Issue by DragonCat168** [aeon0/botty#176]
Hello,
When finishing Pindle run, the show_items button does't seem to work and the char exit game directly.
Loot didn't happen.
Something wrong?

Thank you.

**Comment by aeon0** [comment]
Hi, please ask your questions in the discord channel. github issues are for bug report. Thus the template you deleted : )

Protip: Run the auto settings botty provides. It will adjust how show loot works (it was switched from hold to toggle lately).
