### ISSUE TITLE
Out of tps

### ISSUE THREAD

**Issue by BartoszJedynak** [aeon0/botty#198]
Botty 0.4.3

hi, every time I turn on the bot, soso only goes to Pindle, after Pindel I have this message: [2021-12-04 12: 54: 44,535] WARNING Out of tps

It is set to go to Pindle, Shenk, Eld

**Comment by nekolr** [comment]
> 

make sure you hava a tp book in your package.

**Comment by BartoszJedynak** [comment]
the problem was the wrong F9 key

**Comment by SwePow** [comment]
User config error
However, on this topic I would like to add a little humanization touch of a configurable random chance of going to Malah to heal and to restock TPs.
