### ISSUE TITLE
d2r.exe crashes while running shop.py

### ISSUE THREAD

**Issue by jagarop** [aeon0/botty#213]
**its not a botty issue**, but prob a d2r.exe memory leak.

after a few hours (not too many) of running shop.py, d2r.exe will crash.

i think a workaround is making a new game after x amount of runs (since i don't have problems running main script).

to reproduce, try to run shop.py overnight.

**Comment by algml11** [comment]
[https://i.imgur.com/nqvXgUX.jpg](url)

**Comment by algml11** [comment]
https://imgur.com/nqvXgUX

**Comment by algml11** [comment]
babarian error
nameerror: name'cv2' is not defined

**Comment by jagarop** [comment]
#374 should fix this issue
