### ISSUE TITLE
Hammerdin not working: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Excitedguy** [aeon0/botty#228]
Is it really a Bug report?
Yes

Botty Version
DEV
Commit number: [3f496af](https://github.com/aeon0/botty/commit/8290b4cc366195d237e50fdcb8fc116c696cb934)

Describe the bug
python src/main.py throws an error when trying to run hammerdin 

To Reproduce
git clone https://github.com/aeon0/botty.git
cd botty
conda env create environment.yml
conda activate botty
python src/main.py

Logs:
Traceback (most recent call last):
  File "src/main.py", line 1, in <module>
    from bot import Bot
  File "C:\Users\Brandon\Downloads\botty\src\bot.py", line 3, in <module>
    from char.hammerdin import Hammerdin
  File "C:\Users\Brandon\Downloads\botty\src\char\hammerdin.py", line 14, in <module>
    class Hammerdin(IChar):
  File "C:\Users\Brandon\Downloads\botty\src\char\hammerdin.py", line 42, in Hammerdin
    def _do_redemption(self, delay: tuple[float, float] = (1.5, 2.0)):
TypeError: 'type' object is not subscriptable

**Comment by Devilbilly** [comment]
Do you have redemption on your hot key and pal?

I found out that pre_buff is not secured, if you miss anything that should be set it will crash like this

**Comment by Excitedguy** [comment]
> 

Yes, I have redemption on my paladin and have it bound to f6 and also set it to f6 in the params.ini file. It uses it properly in previous commits,

**Comment by aeon0** [comment]
This is a python 3.8 vs python 3.9 Issue. Please run these commands:
```cmd
conda env remove --name botty
conda env create environment.yml
conda activate botty
python src/main.py
```
