### ISSUE TITLE
Bug "force_move"?

### ISSUE THREAD

**Issue by Andrey5Ka** [aeon0/botty#308]
There is no "force_move"! I did not install it ( force_move=) left it empty because it is not in the game, you need to click with the mouse.
botty/src/char/i_char.py

Line 102 in 1f482d5

 keyboard.send(self._config.char["force_move"]) 

if force_move:
keyboard.send(self._config.char["force_move"])
else:
mouse.click(button="left")

Why is there no left mouse click?

**Comment by nekolr** [comment]
> There is no "force_move"! I did not install it ( force_move=) left it empty because it is not in the game, you need to click with the mouse. botty/src/char/i_char.py
> 
> Line 102 in [1f482d5](https://github.com/aeon0/botty/commit/1f482d5dcefc121692dd8a1add7070b57432423a)
> 
> keyboard.send(self._config.char["force_move"])
> 
> if force_move: keyboard.send(self._config.char["force_move"]) else: mouse.click(button="left")
> 
> Why is there no left mouse click?

not a bug, it can be set in the game settings(control settings).
