### ISSUE TITLE
[v0.5.0-dev] Nihlatak stairs template needs to be improved

### ISSUE THREAD

**Issue by kozfelipe** [aeon0/botty#313]
When mercenary gets on top of the stairs the template cannot be recognized. The template needs more references

`
Wanted to select ['NI1_STAIRS', 'NI1_STAIRS_2', 'NI1_STAIRS_3', 'NI1_STAIRS_4'], but could not find it
`

**Comment by aeon0** [comment]
Maybe a random tele jump could also resolve the issue.
