### ISSUE TITLE
I got out of tps error in pindle while tome is full … fire sors . Another bug which happenes today is that she is buying potions every run and full the stash any help ?

### ISSUE THREAD

**Issue by sashy10** [aeon0/botty#340]
**Is it really a Bug report?**
If you have questions regarding setup or feature information/requests, please consider asking in the Discord channel: https://discord.gg/Jf3J8cuXWg. The Github issues section is for bug reports only.

**Botty Version**
What version of botty are you running? Are you using a pre-compiled release? Which one. Are you using the latest master branch? On which commit?

**Describe the bug**

**To Reproduce**
3. etc.

**Expected behavior**

**Screenshots / Video**
If applicable, add screenshots or even better a short video of the error happening to help explain your problem. Botty often automatically makes screenshots when something goes wrong. Add these also.

**Logs**
Add the relevant part of the info.log in this section. Either upload it as a fail or copy-paste the relevant part in here.

**Additional info**
Add any other information about the problem here.

**Comment by aeon0** [comment]
Please fill out the questions of the bug report properly.

But it does already read like a setup issue. Any off or a combination off:
- F9 auto settings not done
- Show belt hotkey not configured properly
- tp hotkey not configured properly

**Comment by sashy10** [comment]
Thanks dude it seems to be f9 thing I am going to try it now thanks a lot
again

**Comment by sashy10** [comment]
Solved with F9 auto adjust .. thanks dude
