### ISSUE TITLE
pickit bug

### ISSUE THREAD

**Issue by SnOwYKY** [aeon0/botty#345]
new version is picking up magic spiked clubs, and also moving them to stash lol? not sure if just me or i did something

**Comment by kozfelipe** [comment]
if you have this line https://github.com/aeon0/botty/blob/master/config/pickit.ini#L150 set to 1 it will pick clubs

**Comment by SnOwYKY** [comment]
lol..

**Comment by aeon0** [comment]
Spikey clubs :heart:
