### ISSUE TITLE
Botty is not working with set equipment

### ISSUE THREAD

**Issue by g0atrance** [aeon0/botty#380]
The not is not working at all while using full Talrasha's set.
Its just moving the mouse at the spawn spot over the end of the stairs and its got stuck with no progress at all.
If I help him to move it continue to do the pindle run normally

**Comment by aeon0** [comment]
has nothing to do with talset. Please fill the template properly, otherwise it is impossible to determine if this is a setup issue or a bug. You can repone or create a new issue when you provide the required information.
