### ISSUE TITLE
Assertion failed in resize.cpp

### ISSUE THREAD

**Issue by polgiron** [aeon0/botty#392]
Hey guys, I'm having an error while trying to run botty, I've filled out param.ini and pressed f9 to auto set the d2 settings, but then I press f10 or f11 and I'm getting this assertion error:

![Capture](https://user-images.githubusercontent.com/8901804/148100273-9565ec27-15a8-471d-bd00-d40e0c329dbe.PNG)

Do you know what I am missing?

PS: I'm using the main.exe compiled version

**Comment by aeon0** [comment]
looks like a access rights issue. So the path to the template exists but still opencv could not load that image.

**Comment by polgiron** [comment]
FYI it's working well by running the python code directly, so as far as I'm concerned you can close the ticket, cheers
