### ISSUE TITLE
Missing "name" data in discord message ['content']

### ISSUE THREAD

**Issue by allsite** [aeon0/botty#421]
![image](https://user-images.githubusercontent.com/6035778/148709197-16276797-4592-4500-af88-8c74a0d2ce79.png)

The generic_api feature in 0.6.2 is omitting the bot's name in the discord message. This will likely break any custom implementations that parsed out the name for various reasons. In my case, I parsed the name and send a custom discord message to a name-specific channel. In general terms, the data should include the name for basic context.

**Comment by aeon0** [comment]
Fixed with #422
