### ISSUE TITLE
Suggestion -> Cube auto transmute flawless gems

### ISSUE THREAD

**Issue by gdurev** [aeon0/botty#427]
It would be nice to have an option to combine 3 of a kind gems in the cube..

**Comment by flapjax** [comment]
I am working on a gem cuber and will probably be able open a PR within a few days. It would exist first as a standalone module like shopper, with the intent to have it integrated with bot routines in the future.

**Comment by Steve6030** [comment]
Implemented under #491

Issue can be closed @mgleed

**Comment by jobithu** [comment]
Closeme
