### ISSUE TITLE
sell-buy tp tome

### ISSUE THREAD

**Issue by crenod** [aeon0/botty#465]
When bot selling tome and after buy it, but inventory columns is not empty - tome may fold to another place.
After, when bot stashing - he drop this tome.

**Comment by kozfelipe** [comment]
tp tome should be stored in the fixed inventory columns not the loot ones

**Comment by aeon0** [comment]
@kozfelipe it can happen that botty picks up sth on accident and then does not stash and when buying tp back the diablo algo puts it into another spot than it previously was.

A workaround could be to check inventory for stashing everytime we go buy tps.

**Comment by mgleed** [comment]
> @kozfelipe it can happen that botty picks up sth on accident and then does not stash and when buying tp back the diablo algo puts it into another spot than it previously was.
> 
> A workaround could be to check inventory for stashing everytime we go buy tps.

This exact change is part of the stashing/ID sequence overhaul currently on ocr branch, should be able to merge soon

**Comment by pirx-pirx** [comment]
I have the same problem ... Tome is in fixed inventory colums and have been lost twice in a serial of runs. Later cant play and game becomes too short without doing any boss.

**Comment by mgleed** [comment]
Fixed in #588
