### ISSUE TITLE
Traverse from a5_town_start to a5_malah (no automatic movement) v.0.6.4

### ISSUE THREAD

**Issue by doschhar** [aeon0/botty#469]
Bot can traverse anywhere even to revive merc etc but if traversing to malah the cursor just hovers a little to my left and does nothing, If I press the mouse button to move to the location pointed by the bot myself the pathing works and vendor is found. Its like the mouse click to move is not initiated by the bot?!

**Comment by doschhar** [comment]
Found the problem, correct operation seems to require the force_move key to been set correctly.
Should maybe added as a hint to the params file.

**Comment by POchej** [comment]
Hello. 
Could you please tell me how to assign a key to "force_move" option?
I don't have this option in the in-game keyboard setup and I'm stuck.

Regards
