### ISSUE TITLE
Feature request > make health manager function standalone

### ISSUE THREAD

**Issue by allsite** [aeon0/botty#482]
This functionality would be really great while actually playing the game. This would mean also supporting various resolutions that real players use. 

In my testing I found v0.5.0 worked as expected - a standalone health_manager.exe functioning in a 720p window. In more recent versions health_manager.exe doesn't exist.

Is it possible to make "Health Manager" an f-key option in main.exe? I feel it would be a nice addition, if it can suppose more resolutions.

**Comment by mgleed** [comment]
Added this to the list of desired features.
