### ISSUE TITLE
Larzuk Doesn't sell tomes, so bot leaves game

### ISSUE THREAD

**Issue by GeorgeWashingtonABCDEFG** [aeon0/botty#486]
v=0.6.4
INFO       Repairing and buying TPs at next Vendor
DEBUG      Traverse from a5_town_start to a5_larzuk
DEBUG      Waiting for Template ['REPAIR_BTN']
DEBUG      Found Match: REPAIR_BTN (100.0% confidence)
DEBUG      Waiting for Template ['TP_TOME', 'TP_TOME_RED']
DEBUG      Could not find any of the above templates
DEBUG      Traverse from a5_town_start to a5_larzuk
DEBUG      Pather: taking a random guess towards (0, 150)
ERROR      Got stuck exit pather
INFO       Force Exit

**Comment by brimmasch** [comment]
what probably happened is the bot sold its tome to Larzuk with the intent to buy it back and:
- the bot didn't have enough money
- the tome didn't fit in the misc tab and was lost
- the bot closed the window too quickly after buying the tome back and the purchase did not complete.

i've seen all three of these (i think) and there could be more ways in which the bot loses the tome that i haven't seen or can't think of.  this code can definitely be more robust.  if the bot finds itself tome-less it needs to quit with an appropriate message (to discord as well) and stop trying.

**Comment by codahq** [comment]
what probably happened is the bot sold its tome to Larzuk with the intent to buy it back and:

the bot didn't have enough money
the tome didn't fit in the misc tab and was lost
the bot closed the window too quickly after buying the tome back and the purchase did not complete.
i've seen all three of these (i think) and there could be more ways in which the bot loses the tome that i haven't seen or can't think of. this code can definitely be more robust. if the bot finds itself tome-less it needs to quit with an appropriate message (to discord as well) and stop trying.

**Comment by GeorgeWashingtonABCDEFG** [comment]
Selling the tome is a dumb way to do this. Bot should never touch anything which is outside the columns allowed in config.
The way to refill tome is to shift right click on tp scroll in vendor that actually sells tomes.

**Comment by mgleed** [comment]
@GeorgeWashingtonABCDEFG 
Please use the Issues template that you deleted to post your log without any context. Once you've done so, we can revisit this issue.
