### ISSUE TITLE
Lighning sorc doesnt attack or attack in wrong direction... and she teleports passing Nihla or Shenk in 2 jumps at least.

### ISSUE THREAD

**Issue by pirx-pirx** [aeon0/botty#501]
Lighning sorc doesnt attack or attack in wrong direction... and she teleports passing Nihla or Shenk in 2 jumps at least.
Any help please
info.log

**Comment by Buzy1984** [comment]
Same problem here

**Comment by mgleed** [comment]
> Lighning sorc doesnt attack or attack in wrong direction... and she teleports passing Nihla or Shenk in 2 jumps at least. Any help please info.log

There is an Issue template for a reason. I need more than a sentence for this--what version you're on, how often it happens, etc.  Doesn't look like the info.log attachment worked either.

This might be fixed on master, see #495

**Comment by Steve6030** [comment]
Screencap fcr in game and upload params.ini

**Comment by pirx-pirx** [comment]
FCR is 75% in game.
And here is params.ini  .... File type not supported, I have to copy and paste

; There is detailed documentation for each parameter in the README.md
[general]
name=Botty
monitor=0
message_api_type=generic_api
custom_message_hook=
logg_lvl=debug
max_game_length_s=380
resume_key=f11
exit_key=f12
auto_settings_key=f9
settings_backup_key=f8
restore_settings_from_backup_key=f7
graphic_debugger_key=f10
randomize_runs=0
difficulty=nightmare
discord_status_count=20
discord_status_condensed=0
info_screenshots=0
loot_screenshots=0
saved_games_folder=
d2r_path=C:\Program Files (x86)\Diablo II Resurrected\D2R.exe
; if you set this field to 1, botty will save the top-most visible character template just after
; the online/offline tab and upon restart will attempt to find the same template to select the char
restart_d2r_when_stuck=0

[routes]
run_trav=0
run_pindle=1
run_eldritch=0
run_shenk=0
run_nihlatak=0
run_arcane=0
run_diablo=0
; Note: You can not split up or change order of eldritch and shenk as botty treats it as a single run
order=run_trav, run_diablo, run_pindle, run_eldritch, run_shenk, run_nihlatak, run_arcane

[char]
; ==========================
; ==== Mandatory Fields ====
; ==========================
; These configs have to be alligned with your d2r settings and char build
type=light_sorc
casting_frames=10
num_loot_columns=5
show_items=alt
inventory_screen=i
force_move=e
tp=f9
belt_rows=4
;note: stand_still can not be the default "shift" as it would interfere with merc healing
stand_still=capslock
;note: this is different from the default hotkey as "~" is for many keyboards not reachable without also pressing altgr
show_belt=k
potion1=1
potion2=2
potion3=3
potion4=4
cta_available=1
weapon_switch=x
battle_orders=f7
battle_command=f8
; ==========================
; ==== Optional configs ====
; ==========================
stash_gold=1
gold_trav_only=0
use_merc=1
; Attack length for barbarians should be as high as 8-10 and even 10-12 for trav/shenk
atk_len_arc=2.5
atk_len_trav=3.0
atk_len_pindle=3.0
atk_len_eldritch=3.0
atk_len_shenk=4.0
atk_len_nihlatak=4.0
;Diablo & Chaos Sanctuary
atk_len_cs_trashmobs=1.5
atk_len_diablo_deseis=5.0
atk_len_diablo_infector=4.0
atk_len_diablo_vizier=2.0
atk_len_diablo=3.0
kill_cs_trash=0
take_health_potion=0.8
take_mana_potion=0.5
take_rejuv_potion_health=0.42
take_rejuv_potion_mana=0.1
heal_merc=0.5
heal_rejuv_merc=0.2
chicken=0.35
merc_chicken=0
belt_rejuv_columns=2
belt_hp_columns=1
belt_mp_columns=1
pre_buff_every_run=1
always_repair=0
id_items=0
open_chests=1

; ===========================
; ==== Builds: Sorceress ====
; ===========================
[sorceress]
teleport=f1
frozen_armor=f3
energy_shield=
thunder_storm=
telekinesis=
static_field=f5

[light_sorc]
; chain_lightning must be bound to left skill (hotkey optional as it shouldnt change)
chain_lightning=f4
; lightning must be right skill, hotkey required
lightning=f2
; frozen orb must be right skill, hotkey recommended to increase safty for you and merc at trav!
frozen_orb=f6

[blizz_sorc]
; ice_blast must be left skill (hotkey optional as it shouldnt change)
ice_blast=
; blizzard must be right skill, hotkey required
blizzard=f2

[nova_sorc]
; nova must be right skill, hotkey required
nova=f2

; =========================
; ==== Builds: Paladin ====
; =========================
[hammerdin]
teleport=f1
concentration=f2
holy_shield=f4
blessed_hammer=f5
vigor=
redemption=
cleansing=

; ==========================
; ==== Builds: Assassin ====
; ==========================
; Currently no Trav implementaiton!
[trapsin]
teleport=f1
skill_left=f8
burst_of_speed=f4
fade=
shadow_warrior=
lightning_sentry=f2
death_sentry=f3


; ===========================
; ==== Builds: Barbarian ====
; ===========================
; Supported runs: Trav, Pindle, Eld, Shenk, Nihlatak (tele only)
; Make sure leap hotkey is set if you do not have Enigma
; Ensure Battle Order/Command hotkeys are set above in the [char] section 
[barbarian]
teleport=
leap=f6
shout=f3
war_cry=f5
find_item=f4
cry_frequency=0.7


; ==========================
; ==== Builds: Necro ====
; ==========================
; Pindle+eld+shenk, no trav (walking only!)
; needs all of these skills
;skill_left is just some ranged damage spell (spear,teeth, nova,etc)
;leave teleport blank for now this build currently is walking only
;tested with something like this https://d2.maxroll.gg/d2planner/3x01067c
[necro]
teleport=
skill_left=f7
bone_armor=f2
clay_golem=f3
raise_skeleton=f4
raise_revive=f1
amp_dmg=f5
corpse_explosion=f6
clear_pindle_pack=0


; ===========================
; ==== Builds: Basic ====
; ===========================
; Supported runs: UNTESTED (this is your job!)
; this will basically continuously left attack, unless right attack is available.
;if the buffs are not set they are not used (they are part of the prebuff setup)

[basic]
teleport=
left_attack=f5
right_attack=f2
buff_1=f8
buff_2=f3


; ===========================
; ==== Builds: Basic Ranged====
; ===========================
; Supported runs: UNTESTED (this is your job!)
; this will basically continuously left attack, unless right attack is available.
;if the buffs are not set they are not used (they are part of the prebuff setup)

[basic_ranged]
teleport=
left_attack=f5
right_attack=f2
buff_1=f8
buff_2=f3


[dclone]
; Normally have known region IP (that we didn't block) for ip hunting
; eg: EU Server expected IP would be 37.244.11.xxx or 37.244.48.xxx and US Server expected IP would be 158.115.222.xxx or 158.115.221.xxx
; region_ips=37.244.11, 37.244.48 (EU) or region_ips=158.115.222, 158.115.221 (US)
region_ips=
; This is the hot ip that we want to get
dclone_hotip=

[advanced_options]
;===== don't touch unless you know what you're doing =====
pathing_delay_factor=4
message_headers=
message_body_template={{"content": "{msg}"}}
message_highlight=1
d2r_windows_always_on_top=0
graphic_debugger_layer_creator=0

**Comment by Stuvros** [comment]
It's all about "stand_still"

**Comment by pirx-pirx** [comment]
I have changed the "stand_still" for "d" instead "capslock" and same mistakes

**Comment by Stuvros** [comment]
And in the game?

**Comment by Stuvros** [comment]
> FCR is 75% in game.

casting_frames=9

**Comment by Stuvros** [comment]
I achieved the same behavior from my light_sorc, but I don't understand how )))

**Comment by pirx-pirx** [comment]
OMG I will try with 9 frames and brightness or I am lost

**Comment by 1NTRUDER-dev** [comment]
I have changed the type=light_sorc to type=sorceress and after that I fixed my missing shortcuts.
That resolved it for me.
