### ISSUE TITLE
Unique Death Cleave Berserker Axe

### ISSUE THREAD

**Issue by Mexarious** [aeon0/botty#524]
I would like to be able to add this to assets/items as there is no picture for unique berserker axe which is Death Cleaver, it is a very good Melee weapon defiantly for Zealer/pvp. I would like to try to get this added so I can loot an ethereal one so I can build a zealer paladin, Thanks in advance.

**Comment by Zwillyzz** [comment]
Me too. I am hoping it is as easy as placing uniq_beserker_axe=2 or uniq_weapon_death_cleaver=2 in the pickit config under Unique weapons.

**Comment by Zwillyzz** [comment]
You need to create the image and save it in your assets folder after you can add the line into pickit using the same name as your file so like uniq_berserk_axe.png would be uniq_berserk_axe=1 in pickit once you've created the asset

**Comment by Mexarious** [comment]
I OBVIOUSLY tried this first. I got a very clear picture of a unid death
cleaver/berserker axe and put it in assets items just like the rest of the
pictures and tried every variation of unid_death_cleaver,
unid_berserker_axe , unid_weapon_berserker_axe and when I run botty at the
top it says it couldn’t find the picture in assests. I also named it five
different ways and used the same picture for each variation, like the same
picture but I copied pasted it five times and named each one different to
try to get it to work. None of them worked

**Comment by Zwillyzz** [comment]
You did something wrong. Maybe the format of the image is incorrect. How did you obtain the image? I used hero editor, added the item, and snipped it while the item was on the ground. Name the image according to how you have it under the pickit file.

Test it with the graphic debugger, if botty does not detect it in console, you did something wrong.
