### ISSUE TITLE
Pindle run is broken after upgrade to 0.6.7

### ISSUE THREAD

**Issue by coding-junkie** [aeon0/botty#559]
**Is it really a Bug report?**
When I downgrade to 0.6.6, everything's fine. It's only happened on 0.6.7. It's not just mine, my friend have the same experience

**Botty Version**
0.6.7

**Describe the bug**
The mouse cursor fluctuated weirdy on the screen and teleport to Pindle didn't work

**Comment by mgleed** [comment]
Don't copy paste params.ini, use a custom.ini file.

**Comment by coding-junkie** [comment]
I extracted the new version and then copy and paste my custom.ini into it.

**Comment by mgleed** [comment]
> I extracted the new version and then copy and paste my custom.ini into it.

Did you ever get this working? This is always some kind of configuration error with force_move keybinds, teleport keybinds, attack keybinds, etc. Also make sure you use "f9"

**Comment by coding-junkie** [comment]
I downgraded to 0.6.6 and everything works fine to me.

**Comment by coding-junkie** [comment]
Closed as can't reproduce on my local
