### ISSUE TITLE
After hunting, it teleports several times and moves out of the range of the item.

### ISSUE THREAD

**Issue by byungsuLee** [aeon0/botty#585]
**Is it really a Bug report?**

**Botty Version**
- 6.7

**Describe the bug**
- After hunting, it teleports several times and moves out of the range of the item.

**To Reproduce**
1. Pindle After hunting
2. teleport
3. teleport
4. teleport

**Expected behavior**

**Screenshots / Video**
https://user-images.githubusercontent.com/94364470/155449627-1ce5345b-2f17-4925-b2be-3786ea55fcc9.mp4

**Logs**
Add the relevant part of the info.log in this section. Either upload it as a fail or copy-paste the relevant part in here.

**Additional info**
Add any other information about the problem here.

**Comment by mgleed** [comment]
> **Is it really a Bug report?**
> 
> **Botty Version**
> 
> * 6.7
> 
> **Describe the bug**
> 
> * After hunting, it teleports several times and moves out of the range of the item.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Pindle After hunting
> 2. teleport
> 3. teleport
> 4. teleport
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots / Video** https://user-images.githubusercontent.com/94364470/155449627-1ce5345b-2f17-4925-b2be-3786ea55fcc9.mp4
> 
> **Logs** Add the relevant part of the info.log in this section. Either upload it as a fail or copy-paste the relevant part in here.
> 
> **Additional info** Add any other information about the problem here.

@byungsuLee are you able to join discord? I don't think this is a bug, most likely a configuration issue.
