### ISSUE TITLE
Telelport capability check issue

### ISSUE THREAD

**Issue by offerduo** [aeon0/botty#587]
TP capability check always fails for both my chars (hammerdin with enigma and sorc).

I think it might be because my low quality picture that affects the tp icon recognition.
Is there anyway we can change the threshold?

For now I have to modify the `_discover_capabilities` to return desired result as a workaround.

**Comment by VladimirMakaev** [comment]
See #600 so you can bypass autodetection if you want. You can also help me collect debugging info if you wanna help fix autodetection by running a branch https://github.com/VladimirMakaev/botty/tree/debug-capabilities and posting an info.log here.

**Comment by mgleed** [comment]
closed by #600
