### ISSUE TITLE
Player Chicken not prioritized over taking potion

### ISSUE THREAD

**Issue by doschhar** [aeon0/botty#599]
Happened to me several times now that instead of chicken the bot first trys to trink potions even so the take potions % are lower then the chicken %:

chicken=0.8
take_health_potion=0.7
take_rejuv_potion_health=0.6

If players for example death teleports (also happens quite often) right into the pindle group he should be hit, fall below chicken% and chicken right away, but instead it starts a wild trinking of potions orgy and health gets lower and lower until he dies.

[2022-02-27 16:31:22,702] INFO         Health Manager is now active
[2022-02-27 16:31:25,814] DEBUG      Found Match: PINDLE_0 (78.4% confidence)
[2022-02-27 16:31:29,261] DEBUG      Teleport cancel detected. Try same teleport action again. (0.0226)
[2022-02-27 16:31:30,470] DEBUG      Drink rejuv potion in slot 3. HP: 59.0%, Mana: 0.0%
[2022-02-27 16:31:30,644] DEBUG      Drink health potion in slot 1. HP: 59.3%, Mana: 0.0%
[2022-02-27 16:31:30,662] DEBUG      Drink mana potion in slot 2. HP: 59.3%, Mana: 0.0%
[2022-02-27 16:31:37,321] DEBUG      Drink mana potion in slot 2. HP: 100.0%, Mana: 49.2%
[2022-02-27 16:31:38,240] DEBUG      Drink health potion in slot 1. HP: 81.2%, Mana: 88.8%
[2022-02-27 16:31:41,422] WARNING    Trying to chicken, player HP 0.0%!
[2022-02-27 16:31:41,906] DEBUG      Waiting for Template ['SAVE_AND_EXIT_NO_HIGHLIGHT', 'SAVE_AND_EXIT_HIGHLIGHT']
[2022-02-27 16:31:41,923] DEBUG      Found Match: SAVE_AND_EXIT_NO_HIGHLIGHT (77.8% confidence)
[2022-02-27 16:31:42,273] WARNING    You have died!

Chicken% should always be prioritized if higher than drinking potions - so the player would be hit and log of immediately and not die drinking potions while getting hit locked. Guess thats what chicken is for?!

or

if potion% is higher then chicken % once the health falls below the chicken % for the first time it should also chicken right away.

**Comment by D2RLegit** [comment]
"Chicken% should always be prioritized if higher than drinking potions"
chicken=0.8
take_health_potion=0.7

You never put chicken higher then pots threshold EVER. Its a bad config. Correct your config and im sure you wont run into this issue.

**Comment by doschhar** [comment]
> Correct your config and im sure you wont run into this issue.

So lets see how the original settings perform:

take_health_potion=0.8
take_rejuv_potion_health=0.42
chicken=0.35

lets say with a bot with 1.000 health. 

Sorc bot teleports right into a group of monsters (eg. the pindle death dive) - human behavior would be to log out immediately or teleport out of the group immediately. Bot does neither, On the contrary, Bot stops to attack and stands still and is hit by the first monster in reach for lets say 100 damage, trinks a potions, giving the next monster time to join in, damage is now 200 per hit, drinks a potion, next monster joins in damage now 300, trinking potions can't keep up with the damage anymore, until bot runs out of potions eventually life is down to the chicken threshold of 350 life or less, now bot tries to chicken but all the monster around had time to join in total damage taken is now in the thousands, Trying to chicken bot dies.   

A full tal rasha sorc with cta died this way. So did my next 4 sorcs.

Not sure if the chicken is triggered as a priority if the health falls under its threshold or the higher percent take_health/rejuv gets triggered first and by that cancelling the chicken -> which it should not. First time health drops below the chicken threshold the bot should chicken as a priority over trying to heal otherwise it will be too late.

**Comment by doschhar** [comment]
> I would join the discord chat to troubleshoot this. You do not have your botty setup correctly. Sorcs do not face check pindle.

she does. 

with the teleport cancel detection bug -> bot says "teleport cancel detected. try same teleport again"
even so the initial teleport went through and teleports once more from the safe attack distance right into pindel.
(doesn't matter by the way to what cast_frames you set the bot, mine would be 8 yet I use 20 ... still happens from time to time)

-> When the robot runs, it goes deep into Pindle Skin and dies #578

> I would join the discord chat to troubleshoot this. You do not have your botty setup correctly. Sorcs do not face check pindle.
I'll try to check by later - right now I'm at work xD

**Comment by doschhar** [comment]
> I invite you to review `botty/src/health_manager.py`

will review!
