### ISSUE TITLE
Pickit: misc_diamond picks up Diamond Bow

### ISSUE THREAD

**Issue by Kellen-Stuart** [aeon0/botty#601]
**Is it really a Bug report?**
Yes, this is a bug.

**Botty Version**
 Botty 0.6.7-dev

**Describe the bug**
In `pickit.ini` there is a setting called `misc_diamond`. If you set this to `1`, the bot is meant to pickup regular diamonds. However, there is an item in the game called `Diamond Bow` which the bot also thinks is a regular diamond. Botty will pickup Diamond Bows if this settings is enabled which is not expected behavior. 

Note: this is low priority, but wanted to at least document this issue.

**To Reproduce**
1. Enable `misc_diamond` in `pickit.ini`
2. Enter a game
3. Drop a Diamond Bow on the ground
4. Watch Botty pickup and stash the Diamond Bow as `misc_diamond`

**Expected behavior**
Botty should not pickup a Diamond Bow

**Screenshots / Video**
I can get a screenshot or video. Let me know if you need one.

**Logs**
Will grab logs next time it happens.

**Additional info**
None.

**Comment by SosaBlack** [comment]
Known issue with current pickit.

If you activate misc_skull you'll get white skull caps. If you activate hotspurs you'll start getting any unique boots with the word boot in it etc. Believe they're shipping a fix with ocr but don't think it's possible to fix with current pickit. Could be wrong.

**Comment by mgleed** [comment]
> Known issue with current pickit.
> 
> If you activate misc_skull you'll get white skull caps. If you activate hotspurs you'll start getting any unique boots with the word boot in it etc. Believe they're shipping a fix with ocr but don't think it's possible to fix with current pickit. Could be wrong.

@Kellen-Stuart 

You can add blacklist items to assets/items to get around these if you need to. See files with prefix `bl_`
