### ISSUE TITLE
TP Issue

### ISSUE THREAD

**Issue by Inferno22** [aeon0/botty#603]
Hammerdin accidently enters open tp i town after buying potions when heading for waypoint. (Act5)

**Comment by mgleed** [comment]
Please fill out the template, provide video, or do something to help us out. Will reopen when you do. Thanks

**Comment by Inferno22** [comment]
Her is some proof.. is the same with tp’s for pindleskin. Hope its enough 🙂


https://user-images.githubusercontent.com/25798480/157303394-097f30cf-e536-410f-b35c-55215ea393c5.MOV
![EFB6774E-CBEE-4B73-9320-DF2E2E66FD50](https://user-images.githubusercontent.com/25798480/157303452-77a9704d-f61a-4a79-a71d-02ca2a8503f3.jpeg)

**Comment by Inferno22** [comment]
**Is it really a Bug report?**
Yes i belive it is

**Botty Version**
Running newest version of Botty V0.7.0

**Describe the bug**
Hammerdin accidently enters open tp i town after buying potions when heading for waypoint. (Act5)

**To Reproduce**
Steps to reproduce the behavior:
1. Go to Act5 run pindle and set it to run Nihlathak next.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots / Video**
Video is uploadet

https://user-images.githubusercontent.com/25798480/157312623-712c3c85-9453-46c1-af0a-2b5c4694ceb3.MOV



**Logs**
The picture is of the log

**Additional info**
Same problem was in the last version [Botty v0.6.7](https://github.com/aeon0/botty/releases/tag/v0.6.7)
