### ISSUE TITLE
It's not an issue, but... (traverse from a5_town_start to a5_malah) v0.6.7

### ISSUE THREAD

**Issue by POchej** [aeon0/botty#604]
Hello.
It's not an issue, but I can't deal with it. 
I found one post on this topic, but no clear answer.
Could someone please tell me how to assign a key to the "force_move=" option in params.ini ?
I don't have this option in the in-game keyboard setup.

Regards.

**Comment by VladimirMakaev** [comment]
This is not the right place for support queries
1) Study Readme
2) Google as it's generic D2R question
3) Use support channel on our discord where other users can help you
