### ISSUE TITLE
Strange situation

### ISSUE THREAD

**Issue by BhaalMG** [aeon0/botty#626]
I am facing a very strange situation. Two characters who stayed overnight doing eldritch simply lost the helmets they were equipped with.

**Comment by Inferno22** [comment]
Yep i have witness that too. I lost a shako 🥲

**Comment by D2RLegit** [comment]
Are you using a remote desktop software?

**Comment by Inferno22** [comment]
I’m not

**Comment by mgleed** [comment]
Please follow the issues template
