### ISSUE TITLE
Go to stash every run (Botty v.0.7.1)

### ISSUE THREAD

**Issue by nicoco1107** [aeon0/botty#633]
Hi,

I am running pindle runs with my blizz sorc. 
My char goes to the stash at the beginning of every run after it has stashed the first found item (fine before, it goes directly to the red portal).
This issue did not appear in v. 0.6.7

Any ideas?

Many thanks.

Nico

**Comment by Steve6030** [comment]
Can you confirm your params value for
```
runs_per_stash=
transmute_every_x_game=
```

**Comment by nicoco1107** [comment]
runs_per_stash=0
transmute_every_x_game=1000

Any issues with this?

**Comment by mgleed** [comment]
@nicoco1107 are you able to run latest master? Made some changes around this, might have fixed the issue.

**Comment by nicoco1107** [comment]
@mgleed - How do I do this? I used to download the .rar file

**Comment by nicoco1107** [comment]
resolved with new release - thanks!

**Comment by mgleed** [comment]
You're welcome!
