### ISSUE TITLE
Feature request: replace image matching with text matching in pickit

### ISSUE THREAD

**Issue by roozhou** [aeon0/botty#649]
It's very inconvenient to add new items and properties in `pickit.ini` since screenshot of texts are needed.
All items and descriptions are being OCRed but the text is not used for identifying. Do the developers have plan to use OCR result instead?

**Comment by mgleed** [comment]
Yes we do, hopefully before long.

**Comment by hwangjanggun** [comment]
> 예, 곧 가능합니다.

지금되는건가오?
