### ISSUE TITLE
Bug Blizz Sorc / moving and Attack

### ISSUE THREAD

**Issue by Greenapple2021** [aeon0/botty#656]
Blizz - Sorc
Please fix the sequence from Attack and moving on Shenk is really horrible to farm it.

Possible to change ice bolt for glacial spike better skill and freezing move around.

**Comment by mgleed** [comment]
You are welcome to make a feature request in the discord

**Comment by Greenapple2021** [comment]
I posted issue to fix the problem u removed post...

wt., 22 mar 2022, 23:02 użytkownik Siksa ***@***.***> napisał:

**Comment by D2RLegit** [comment]
I would love to see a better solution to this but i think I nailed it pretty well.

**Comment by Greenapple2021** [comment]
Blizz Sorc porting in middle mobs arena, then she spawn ice bolt, would be nice to edit it and should be like same light sorc from distance attack not with porting.
Also glacier spike wont help much since everything is cold immune. / that help much if u playing on normal or nightmare, hell mobs without immun are freezed.
