### ISSUE TITLE
Not Choosing Fridgid WP

### ISSUE THREAD

**Issue by WHOZDURTY** [aeon0/botty#71]
FIXED

**Comment by WHOZDURTY** [comment]
seemed to have fixed the issue

**Comment by WHOZDURTY** [comment]
Still having a issue where no magic/rare/unique items are being looted, only full rejuvs and flawless amethysts which I have selected.

**Comment by aeon0** [comment]
1) It seems you just deleted the issue template, it is there for a reason
2) If you have a new bug, please also create a new issue template
