### ISSUE TITLE
bot wont run with 0.7.3

### ISSUE THREAD

**Issue by blackxthink** [aeon0/botty#722]
**Is it really a Bug report?**
If you have questions regarding setup or feature information/requests, please consider asking in the Discord channel: https://discord.gg/Jf3J8cuXWg. The Github issues section is for bug reports only.

**Botty Version**
What version of botty are you running? Are you using a pre-compiled release? Which one. Are you using the latest master branch? On which commit?
0.7.3 (master-branch)

**Describe the bug**
Entering the number 4 then enter, it gives me an error.
env is installed (still runs fine under 0.7.2)

**To Reproduce**
1. run run.bat
2. Type "4" press enter
3. bugs happens here

**Screenshots / Video**

![image](https://user-images.githubusercontent.com/48074916/164487791-2fda982c-44c3-4a20-ac2d-9c8ebce5a9e7.png)

**Comment by Redman920** [comment]
Are you trying to use the old config files? There was an update and the Params.ini changed and will error out.

**Comment by blackxthink** [comment]
> 

I changed the routes part for the new one in my params.ini

i thought it was the only part that changed.
Let me see if i resetup the params.ini

**Comment by weteamsteve** [comment]
The error is telling you it is looking for `max_runtime_before_break_m`

For example, mine is `max_runtime_before_break_m=120`
