### ISSUE TITLE
"Backup D2R current settings" error

### ISSUE THREAD

**Issue by drallcom3** [aeon0/botty#739]
**Botty Version**
0.7.3 release

**Describe the bug**
Fresh install.
Press F8 for "Backup D2R current settings".
Get error.

**To Reproduce**
1. New bot install.
2. Start bot and have D2R open as required.
3. Press F8

**Expected behavior**
No error message.

**Logs**
```
D2R settings backed up successfully.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "keyboard\_generic.py", line 58, in process
  File "keyboard\__init__.py", line 218, in pre_process_event
  File "keyboard\__init__.py", line 649, in <lambda>
  File "main.py", line 85, in <lambda>
  File "utils\auto_settings.py", line 47, in backup_settings
KeyError: 'AdditionalLaunchArguments'
```

**Additional info**
Bot works fine otherwise.

**Comment by mgleed** [comment]
> **Botty Version** 0.7.3 release
> 
> **Describe the bug** Fresh install. Press F8 for "Backup D2R current settings". Get error.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. New bot install.
> 2. Start bot and have D2R open as required.
> 3. Press F8
> 
> **Expected behavior** No error message.
> 
> **Logs**
> 
> ```
> D2R settings backed up successfully.
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "threading.py", line 973, in _bootstrap_inner
>   File "threading.py", line 910, in run
>   File "keyboard\_generic.py", line 58, in process
>   File "keyboard\__init__.py", line 218, in pre_process_event
>   File "keyboard\__init__.py", line 649, in <lambda>
>   File "main.py", line 85, in <lambda>
>   File "utils\auto_settings.py", line 47, in backup_settings
> KeyError: 'AdditionalLaunchArguments'
> ```
> 
> **Additional info** Bot works fine otherwise.

Don't copy paste your params.ini file between versions.
