### ISSUE TITLE
[Feature] End script if not able to resurrect mercenary

### ISSUE THREAD

**Issue by kozfelipe** [aeon0/botty#747]
sometimes when we are in low gear, we have not much gold and we are highly dependant on mercenary. Im requesting a feature to be able to quit in case all of the gold to resurrect mercenary ran out to prevent unnecessary deaths and broken gear without him
if use_merc=1

**Comment by Enndee** [comment]
could be implemented as use_merc=2 and quit when failing to recover him ..

**Comment by jagarop** [comment]
issues are for bug report only, please use discord for fr.
