### ISSUE TITLE
Chicken save & exit mouse conflict

### ISSUE THREAD

**Issue by mgleed** [aeon0/botty#75]
**Botty Version** 
An older version of my require_merc branch of my fork, core is botty 2.2. chicken subroutine was unchanged

**Describe the bug**
Unusual rare behavior on chicken when trying to click save & exit. Could it be due to the bot continuing to try to move or perform attack sequence simultaneously when the chicken occurs and causes a conflict in mouse movement?

**To Reproduce**
-Force a chicken during an attack sequence or movement sequence, then observe mouse attempt to save&exit.

**Expected behavior**
-Save&exit should be clicked

**Screenshots / Video**
https://user-images.githubusercontent.com/9866239/142743819-c3a2376b-3465-454d-b4c0-f5db118dc425.mp4

**Logs**
![Log](https://user-images.githubusercontent.com/9866239/142743889-4950bdff-2510-4c99-9d35-3b10cd11b3c7.png)

**Comment by aeon0** [comment]
I would hope that two changes make this 1) less likely to occur 2) if it occurs have another go to click save&exit:

retry save and exit until loading screen is reached
https://github.com/aeon0/botty/commit/c22f133
43daf7c862c021ddaa20b4b1001d2c15d
https://github.com/aeon0/botty/pull/44/files

**Comment by aeon0** [comment]
Sry, didnt want to close @mgleed, if you think that is enough (both changes are post v0.2.2), close it. If not you can bug me more with it : )

**Comment by mgleed** [comment]
> Sry, didnt want to close @mgleed, if you think that is enough (both changes are post v0.2.2), close it. If not you can bug me more with it : )

Sounds good, must have missed that change in #44 . Like I mentioned before, my character attempted to grab corpse every run after a single death after I movrd the kill thread line up, but seems like it probably works otherwise. If there are any other issues I run into I'll reopen.
