### ISSUE TITLE
Hammerdin using Vigor

### ISSUE THREAD

**Issue by surviveqwe** [aeon0/botty#757]
Is it really a Bug report?
Yes

Botty Version
Pre-compiled 0.7.3

Describe the bug
Hammerdin throw hammers with Vigor. It doesn't switch to Concentration aura...

Expected behavior
It was working on 0.7.1

**Comment by p0w3rD** [comment]
I have the same issue. And also when is trying to talk with the mercs, it's saying "Not now, not in town", like trying to throw the hammer in the town.

**Comment by drallcom3** [comment]
#749

**Comment by sryer1989** [comment]
I think this is a pathing issue as sometimes my hdin will turn on concentration and sometimes not. Depends where he is in the map before swinging hammers. If he gets to the right spot he switches to conc. If mobs cut him off, he doesn't.
