### ISSUE TITLE
Rejuv potions save to stash

### ISSUE THREAD

**Issue by namdnas23** [aeon0/botty#778]
I have Rejuv pots to be picked up but current bot only picks up if needed in the belt bar. Is there a plan forward to incorporate saving rejuv's to stash for other characters to be able to use them or to trade on forums for other items as many people don't want to farm themselves for it.

**Comment by namdnas23** [comment]
@derek337 Yes the PNG is already there as well as it is already inside of the pickit as well. The problem is that the bot will only pickup rejuv pots ONLY when the belt is empty of them. The code needs to be updated so that the character will keep picking them up even when the belt is full and then stash them.

**Comment by jagarop** [comment]
not a bug
