### ISSUE TITLE
Teleport working not correctly

### ISSUE THREAD

**Issue by Dragemko** [aeon0/botty#779]
The character is lightning sorc. At first, the teleport to the Pindel works fine. But after the occurrence of this message in the log " Doing runs: odict_keys(['run_pindle']) ", teleportation shifts indoors from the Pendel to the left and up. Not much, but it leads to the death of the character, as teleportation takes place in a crowd of monsters.  

Can I remove this procedure or disable it?

**Comment by D2RLegit** [comment]
probably your cast rate isnt 11ish or your missing a prebuff hotkey. Or your running vm with not enough resources.

**Comment by Dragemko** [comment]
> probably your cast rate isnt 11ish or your missing a prebuff hotkey. Or your running vm with not enough resources.

TNX!!! cast rate - 8! Changed to 11 and voila!

**Comment by namdnas23** [comment]
I would say check the fcr breakpoints for your correct cast rate frame and change it as indicated. @D2RLegit Sounds right with what has been stated.
