### ISSUE TITLE
Is it possible to add logic to pick up a corpse after death in game?

### ISSUE THREAD

**Issue by JoungH** [aeon0/botty#782]
**Is it really a Bug report?**
If you have questions regarding setup or feature information/requests, please consider asking in the Discord channel: https://discord.gg/Jf3J8cuXWg. The Github issues section is for bug reports only.

**Botty Version**
v 0.73

What version of botty are you running? Are you using a pre-compiled release? Which one. Are you using the latest master branch? On which commit?

**Describe the bug**

If you die in the game, it restarts, but you turn around without picking up the corpse and continue to die.
By resurrecting only the mercenaries, they run out of money and run around barefoot and only experience points are flying.
Is it possible to add logic to pick up a corpse when you die?

**To Reproduce**
3. etc.

**Expected behavior**

**Screenshots / Video**
If applicable, add screenshots or even better a short video of the error happening to help explain your problem. Botty often automatically makes screenshots when something goes wrong. Add these also.

**Logs**
Add the relevant part of the info.log in this section. Either upload it as a fail or copy-paste the relevant part in here.

**Additional info**
Add any other information about the problem here.

**Comment by D2RLegit** [comment]
Update your Botty.

**Comment by JoungH** [comment]
> Update your Botty. This was a glitch that's been fixed for a while and the logic was implimented a long time ago.

My botty version is 0.7.3, is there a newer version?
I downloaded it yesterday, but I wonder if it is the latest version.

**Comment by derek337** [comment]
> > Update your Botty. This was a glitch that's been fixed for a while and the logic was implimented a long time ago.
> 
> My botty version is 0.7.3, is there a newer version? I downloaded it yesterday, but I wonder if it is the latest version.

0.7.3 is the latest official released version, If you run the application from src you can get updates faster. 
https://github.com/aeon0/botty/blob/master/development.md#getting-started

**Comment by jagarop** [comment]
fixed on current git version, will be available on next release.
