### ISSUE TITLE
Korean nickname. I don't eat dead bodies after I die

### ISSUE THREAD

**Issue by nate0n** [aeon0/botty#784]
**Is it really a Bug report?**
If you have questions regarding setup or feature information/requests, please consider asking in the Discord channel: https://discord.gg/Jf3J8cuXWg. The Github issues section is for bug reports only.

**Botty Version**
What version of botty are you running? Are you using a pre-compiled release? Which one. Are you using the latest master branch? On which commit?

**Describe the bug**

**To Reproduce**
3. etc.

**Expected behavior**

**Screenshots / Video**
If applicable, add screenshots or even better a short video of the error happening to help explain your problem. Botty often automatically makes screenshots when something goes wrong. Add these also.

**Logs**
Add the relevant part of the info.log in this section. Either upload it as a fail or copy-paste the relevant part in here.

**Additional info**
Add any other information about the problem here.

**Comment by nate0n** [comment]
한글 닉네임 시체를 안먹어요 도와주세요 뭘 수정해야 하나요

**Comment by mgleed** [comment]
Will you provide a screenshot of the corpse text? It is most likely an issue with font.

**Comment by nate0n** [comment]
> 시체 텍스트의 스크린샷을 제공하시겠습니까? 폰트 문제일 가능성이 큽니다.

 # Handle picking up corpse in case of death
        if (corpse_present := is_visible(ScreenObjects.Corpse)):
            self._previous_run_failed = True
            view.pickup_corpse()
            wait_until_hidden(ScreenObjects.Corpse)
            belt.fill_up_belt_from_inventory(Config().char["num_loot_columns"])
        self._char.discover_capabilities()
        if corpse_present and self._char.capabilities.can_teleport_with_charges and not self._char.select_tp():
            keybind = self._char._skill_hotkeys["teleport"]
            Logger.info(f"Teleport keybind is lost upon death. Rebinding teleport to '{keybind}'")
            self._char.remap_right_skill_hotkey("TELE_ACTIVE", self._char._skill_hotkeys["teleport"])

        # Check for the current game ip and pause if we are able to obtain the hot ip
        if Config().dclone["region_ips"] != "" and Config().dclone["dclone_hotip"] != "":
            cur_game_ip = get_d2r_game_ip()
            hot_ip = Config().dclone["dclone_hotip"]
            Logger.debug(f"Current Game IP: {cur_game_ip}   and HOTIP: {hot_ip}")
            if hot_ip == cur_game_ip:
                self._messenger.send_message(f"Dclone IP Found on IP: {cur_game_ip}")
                print("Press Enter")
                input()
                os._exit(1)
            else:
                Logger.info(f"Please Enter the region ip and hot ip on config to use")

        # Run /nopickup command to avoid picking up stuff on accident
        if not self._ran_no_pickup and not self._game_stats._nopickup_active:
            self._ran_no_pickup = True
            if view.enable_no_pickup():
                self._game_stats._nopickup_active = True
                Logger.info("Activated /nopickup")
            else:
                Logger.error("Failed to detect if /nopickup command was applied or not")

        self._game_stats.log_exp()

        self.trigger_or_stop("maintenance")

**Comment by Red-NaDa** [comment]
![ss01](https://user-images.githubusercontent.com/105877394/169354499-906c2db9-cf3d-4f82-9b9e-2546e1b5bbc6.png)
I'm having the same problem

**Comment by Red-NaDa** [comment]
> 시체 텍스트의 스크린샷을 제공하시겠습니까? 폰트 문제일 가능성이 큽니다.


![Screenshot005](https://user-images.githubusercontent.com/105877394/169360308-c360ef1d-2b9f-4869-9355-9299459e7979.png)
I think the Korean nickname font is different when I die

**Comment by nate0n** [comment]
> > 시체 텍스트의 스크린샷을 제공하시겠습니까? 폰트 문제일 가능성이 큽니다.
> 
> ![Screenshot005](https://user-images.githubusercontent.com/105877394/169360308-c360ef1d-2b9f-4869-9355-9299459e7979.png) I think the Korean nickname font is different when I die

**Comment by nate0n** [comment]
![image](https://user-images.githubusercontent.com/105841995/169373706-e85c5591-69ea-4c5c-8e4e-695ffcd167e9.jpg)

**Comment by nate0n** [comment]
> Will you provide a screenshot of the corpse text? It is most likely an issue with font.

![image](https://user-images.githubusercontent.com/105841995/169373868-68dccc15-0688-46bf-b7f4-f570efc5a648.jpg)

**Comment by mgleed** [comment]
I should be able to fix this, I just need a bit of time.

**Comment by s29066047** [comment]
There is the same problem with Chinese name…

**Comment by mgleed** [comment]
closed by #791
