### ISSUE TITLE
Offline line was Kerik seontaekchang

### ISSUE THREAD

**Issue by hyunwoo80** [aeon0/botty#785]
Automatic execution works well, but it's not online, but there's a Kerik selection window offline, so it's stopped. Unable to proceed.
Version is 0.7.
![jjj](https://user-images.githubusercontent.com/105896025/169430090-1e552eaa-97b8-4742-a334-8103d2a2d88f.jpg)
3

**Comment by ironkan** [comment]
It is embarrassing.. korean..

**Comment by jagarop** [comment]
theres a pattern in bug report for a reason

**Comment by Eunsukjoon** [comment]
Thanks

2022년 5월 30일 (월) 오전 7:24, jagarop ***@***.***>님이 작성:
