### ISSUE TITLE
How can I solve this problem??

### ISSUE THREAD

**Issue by ironkan** [aeon0/botty#787]
**Botty Version**
0.7.3

**Describe the bug**
1. When I get out of the game, Online tab is converted to Offline tab.. automatically.. after selecting Online tab only once(Message "Fail to... blah blah"), Botty do not anything. (It hasn't been changed to Online tab)

2. Window(1280*720) ploblem - clicking miss

**Screenshots / Video**

1.
![1](https://user-images.githubusercontent.com/105576923/169457244-b2b77a25-7053-454d-bff4-46a65955d999.png)

2. 
![1](https://user-images.githubusercontent.com/105576923/169566857-89c167fd-822d-442c-9719-8f1e52cd5a3d.png)

**Comment by namdnas23** [comment]
Without having the bot change automatically back to the online tab and then choosing the correct character this isn't able to be done. The servers have been super unreliable as of lately even for me.

**Comment by ironkan** [comment]
Aha.. Thnaks for the rep. but That wasn't any help...

**Comment by ironkan** [comment]
Aha.. Thnaks for the rep. but That wasn't any help...

**Comment by ironkan** [comment]
Aha.. Thnaks for the rep. but That wasn't any help...

**Comment by ironkan** [comment]
what a pity.. Is there someone who's good at programming?? haha...

**Comment by definitelynotsosa** [comment]
The game window changes due to your monitor turning off or on it's a windows/d2r thing not a botty thing and can only be fixed by resetting the window size manually

**Comment by ironkan** [comment]
THANKS!!
