### ISSUE TITLE
Suggestion: mouse click over online tab before finding/clicking play button

### ISSUE THREAD

**Issue by Tntrance** [aeon0/botty#789]
**Is it really a Bug report?**
If you have questions regarding setup or feature information/requests, please consider asking in the Discord channel: https://discord.gg/Jf3J8cuXWg. The Github issues section is for bug reports only.

**Botty Version**
What version of botty are you running? Are you using a pre-compiled release? Which one. Are you using the latest master branch? On which commit?

**Describe the bug**
I’ve noticed that as of recent the bot keeps getting stopped at the play button due to blizzards lack of server upkeep. After a game has ended the tab on the right will default to Offline characters instead of Online

**To Reproduce**
1. Its random. Whenever Bnet or your own computer is having network issues.
2. Script will stop at looking for play button phase

**Expected behavior**
Bot will mouse hover and click on “Online” tab on the right hand side. Then continue to look for play button.

**Screenshots / Video**
If applicable, add screenshots or even better a short video of the error happening to help explain your problem. Botty often automatically makes screenshots when something goes wrong. Add these also.

**Logs**
Add the relevant part of the info.log in this section. Either upload it as a fail or copy-paste the relevant part in here.

**Additional info**
Add any other information about the problem here.

**Comment by zutto** [comment]
`This project is for informational and educational purposes only and is not meant for online usage.`

first textline in https://github.com/aeon0/botty/blob/master/README.md

**Comment by roozhou** [comment]
https://github.com/aeon0/botty/pull/834
