### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by PAka122** [aeon0/botty#793]
- [ ]
![1](https://user-images.githubusercontent.com/106075025/169807173-b65d4a8f-791a-4626-84a7-6c4880ae6ba2.jpg)

please help me

**Comment by bad-magick** [comment]
Are you using an older params config from a previous version?

**Comment by PAka122** [comment]
> 
Should I use a different version?

**Comment by namdnas23** [comment]
Download latest release and update params.ini for your character. Also you are running compiled version correct? If not make sure to follow directions to run the development build.

**Comment by PAka122** [comment]
> 

I used the latest release and ran main.exe after compiling, but that error occurred.

**Comment by jagarop** [comment]
not a bug
