### ISSUE TITLE
There is no gray_mancatcher image.

### ISSUE THREAD

**Issue by anoldan** [aeon0/botty#796]
**Is it really a Bug report?**
If you have questions regarding setup or feature information/requests, please consider asking in the Discord channel: https://discord.gg/Jf3J8cuXWg. The Github issues section is for bug reports only.

There is no image of a mancatcher that has become an infinite space material with this patch.

**Botty Version**
What version of botty are you running? Are you using a pre-compiled release? Which one. Are you using the latest master branch? On which commit?

**Describe the bug**

**To Reproduce**
3. etc.

**Expected behavior**

**Screenshots / Video**
If applicable, add screenshots or even better a short video of the error happening to help explain your problem. Botty often automatically makes screenshots when something goes wrong. Add these also.

**Logs**
Add the relevant part of the info.log in this section. Either upload it as a fail or copy-paste the relevant part in here.

**Additional info**
Add any other information about the problem here.

**Comment by MiniMini72** [comment]
I made it with Jueun's item
I've glued Superior to another item, but I don't know if it'll work. I'm testing i
<img width="61" alt="gray_weapon_mancatcher" src="https://user-images.githubusercontent.com/105991173/170272856-8902a271-cc80-4004-9c9e-2b301358bd30.png">
![gray_weapon_superior_mancatcher](https://user-images.githubusercontent.com/105991173/170272860-dbdf2f51-5ce4-4b7a-9908-505826deee8e.png)
<img width="61" alt="white_mancatcher" src="https://user-images.githubusercontent.com/105991173/170272864-eabbf4b8-1ad7-4bcc-a520-e9931cac31ff.png">
![white_superior_mancatcher](https://user-images.githubusercontent.com/105991173/170272868-f7bf1d2d-13e8-42b9-8927-f94df47c05d4.png)
t

**Comment by mgleed** [comment]
Nice!
