### ISSUE TITLE
한국이름 시체를 수거 하지않아요

### ISSUE THREAD

**Issue by hwangjanggun** [aeon0/botty#798]
한국이름 캐릭터입니다

죽으면 시체를 수거하지않아요 

어떻게 해야하나요

이전버전은 수거가 됩니다

**Comment by fretl** [comment]
How about using google translate?

**Comment by namdnas23** [comment]
Korean name character

We don't collect the body when we die.

What should I do

The previous version will be collected

(Google Translated line for line.)

**Comment by namdnas23** [comment]
The other question is that is the Korean character only in Korean or are you running the client with Korean language selected as well. Bot has to be ran in English language only. Rerun as English if you're not and run autosetting configuration tool.

**Comment by ironkan** [comment]
It is embarrassing.. korean..

**Comment by jagarop** [comment]
english pls

**Comment by ironkan** [comment]
창피하다 한국 욕먹이지 말고 영어좀 익히고 글싸라
