### ISSUE TITLE
rare bonweave boots를 먹지 않습니다.

### ISSUE THREAD

**Issue by choitout** [aeon0/botty#800]
pickit.ini 파일을 확인해도 문제가 해결되지 않네요.

현재 제 설정 상태입니니다. rare_boneweave_boots=1

> 

don't pick up rare bonweave boots. (+other boots)

my pickit.ini = rare_boneweave_boots=1

**Comment by namdnas23** [comment]
English please.

**Comment by choitout** [comment]
pickit.ini 파일을 확인해도 문제가 해결되지 않네요.

현재 제 설정 상태입니니다. rare_boneweave_boots=1

> 

don't pick up rare bonweave boots. (+other boots)

my pickit.ini = rare_boneweave_boots=1

**Comment by namdnas23** [comment]
Check within the assets folder for a .png which also is named rare_boneweave_boots.png
If that is missing then you will either need to add it or check the github repository and download that file to your assets folder.

**Comment by jagarop** [comment]
not a bug

**Comment by ironkan** [comment]
창피하다 한국 욕먹이지 마라
