### ISSUE TITLE
There's a lot of course

### ISSUE THREAD

**Issue by hwangjanggun** [aeon0/botty#801]
Hello, I am Korean
Please understand even if I am not good at English
I'm using a translator
I have a lot of questions Help me

1. They don't pick up bodies with Korean names
It doesn't help me at all to find a solution in the issue and to read and execute a person named NateOn

2.My hunting routes are pins and Eldridge
The pins will go further than the telpochi, and you'll die, or you'll get chicken, and I want it to run well in its original position

3. I would like to give a potion when I give an item after hunting 
I'd like to pick up only the items designated by Gold and Pickett 
I don't want to pick up potions Is there any way?
![39A85B12-A627-40EE-9F59-E4A508A57F85](https://user-images.githubusercontent.com/105962020/170455682-593ba2fd-cb1c-4b85-b435-92ca89896d1f.png)

**Comment by herrtd** [comment]
진지하게 번역까지하셔서 글을쓰셨네ㅎㅎ

1번은 https://open.kakao.com/o/s8P4lJCd 톡주세요

2번 같은 질문 경우는 보통 오토스킬옵션 켜두면 저렇게 되던데
오토스킬 켜 두셨으면 엘드리치 에서도 더멀리 갈텐데 확인한번해보세요.
그리고 F11번으로 오토 실행전에 F9번으로 설정맞춰주고 실행하세요.

3번 은 사냥후 물약 준다는게 무슨말인지 모르겠네요
보통 물약없으면 알아서 말라한테서 구매합니다.

**Comment by zutto** [comment]
1. https://github.com/aeon0/botty/pull/791 - already fixed, you'll need to compile new version of botty manually or wait until next release.

2. `The pins will go further than the telpochi` (teleports too far like in the Image I assume)
Change cast_frames in params.ini should be higher than your characters FCR breakpoint (and server/computer lag accounted as well!) 14 is a safe value.

4. `I don't want to pick up potions Is there any way?`
if you dont want to pick up potions ->pickit.ini change these:
```
misc_rejuvenation_potion=1
misc_full_rejuvenation_potion=1
misc_super_healing_potion=1
misc_super_mana_potion=1
misc_greater_healing_potion=1
misc_greater_mana_potion=1
```
to 0

**Comment by jagarop** [comment]
not a bug
