### ISSUE TITLE
What do these things mean?

### ISSUE THREAD

**Issue by jeremyohs** [aeon0/botty#805]
Botty: Status Report
╭─────┬───┬───┬───┬────┬───╮
│ Run │ I │ C │ D │ MD │ F │
├─────┼───┼───┼───┼────┼───┤
│ Pin │ 1 │ 0 │ 0 │ 0  │ 1 │
├─────┼───┼───┼───┼────┼───┤
│ Eld │ 0 │ 0 │ 0 │ 0  │ 0 │
├─────┼───┼───┼───┼────┼───┤
│ Shk │ 0 │ 1 │ 0 │ 0  │ 0 │
├─────┼───┼───┼───┼────┼───┤
│  T  │ 1 │ 1 │ 0 │ 0  │ 1 │
╰─────┴───┴───┴───┴────┴───╯

I   C   D   MD   F    ?

**Comment by chongjae** [comment]
I - Item
C - Chiken
D - Death
MD - Merc Death
F - Fail

**Comment by jagarop** [comment]
not a bug
