### ISSUE TITLE
 I'd like to change my skills when I hunt

### ISSUE THREAD

**Issue by hwangjanggun** [aeon0/botty#807]
**Is it really a Bug report?**
If you have questions regarding setup or feature information/requests, please consider asking in the Discord channel: https://discord.gg/Jf3J8cuXWg. The Github issues section is for bug reports only.

**Botty Version**
What version of botty are you running? Are you using a pre-compiled release? Which one. Are you using the latest master branch? On which commit? 0.73

**Describe the bug**

**To Reproduce**
3. etc.

**Expected behavior**

**Screenshots / Video**
If applicable, add screenshots or even better a short video of the error happening to help explain your problem. Botty often automatically makes screenshots when something goes wrong. Add these also.

**Logs**
Add the relevant part of the info.log in this section. Either upload it as a fail or copy-paste the relevant part in here.

**Additional info**
Add any other information about the problem here.

Hello, I am Korean
I'm using a translator because I can't speak English 
I'd appreciate it if you could understand 

Thank you so much for helping me 
It's interesting and fun to do it one by one

If you look at the pindle, I have pins, Eldridge Shank, and so on
I want to change the way we hunt

So I was looking for it, and there was a file like this

I thought I could edit it here, so I did it 

No, it's not this way?

Shoots lightening from the pins 

I'd like to cancel the lightning and use the chain lightning 

What should I do?

Thank you for helping me in advance
![603B0914-EA70-4A0A-A262-2021410D6164](https://user-images.githubusercontent.com/105962020/170709707-2f3a4d9d-0b4c-4365-946c-59639cae2044.png)
![Uploading 04143A87-A313-4127-9824-DA1B7B3A3330.png…]()

**Comment by hwangjanggun** [comment]
![Uploading 45E0F003-40F5-48F9-9F67-57A096DE89E1.jpeg…]()

**Comment by hwangjanggun** [comment]
![43A8B07A-2E6A-4017-AE59-65ED2953B920](https://user-images.githubusercontent.com/105962020/170709949-5c216ded-a684-4832-99a2-233d3ab35d6a.jpeg)

**Comment by hwangjanggun** [comment]
![Uploading F7F8332C-F4F0-4225-9E54-C6CF90CAEB53.jpeg…]()

**Comment by jagarop** [comment]
issues is only for bugs, not for requests
