### ISSUE TITLE
Image error, and won't start running.

### ISSUE THREAD

**Issue by Brobbi** [aeon0/botty#809]
im using the v.0.7.3 version

**Describe the bug**
the bot is loading the game, and joining the game. after it checks my inventory, it gives me this error 

opencv(4.5.5) d:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:assertion failed) !_src.empty() in function 'cv::cvtcolor'

how do i fix this?

i have tried to run the d2bug f10 and f9. nothing worked.

**Comment by zutto** [comment]
Fix your file permissions/run botty as an admin/make sure your disk isn't broken.

**Comment by mgleed** [comment]
Please follow the template. I can't debug this.
