### ISSUE TITLE
Need help with this issue, cant run botty:( 1k fg who slove it:D

### ISSUE THREAD

**Issue by balint0203** [aeon0/botty#813]
The problem:
https://imgur.com/HH4hXvi

in my parmas.ini setup
show_belt=k

and ingame chat show this error message:
https://imgur.com/VaTKPir

can offer 1k fg who can slove this problem, cuz i cant sadly

**Comment by jagarop** [comment]
not a bug

**Comment by balint0203** [comment]
> not a bug

where can i get help then if not here?

**Comment by zutto** [comment]
> > not a bug
> 
> where can i get help then if not here?

https://discord.gg/Jf3J8cuXWg - linked in the README

also:
use the F9 key when you first run botty, and configure your hotkeys properly.
