### ISSUE TITLE
Several issues...

### ISSUE THREAD

**Issue by Timtook5858** [aeon0/botty#815]
1.  Cain is not working to identify in act 5.  I don't know if he works in the other acts or not. There is another post about this many days ago.  To get around this, I carry an ID tome in my inv.

2.  I keep getting EXP OCR Error; experience: is not in list.  I see nothing in the config files about experience, so I don't know how to fix this.  It doesn't seem to cause any issues.

3.  Gambling does not appear to work.  Is it working for anyone?

4.  The item pickup is missing several uniques that I'd like to pick up that I cannot enable.  I attempted taking a picture of the unique item name as a PNG, putting it in the asset folder, and then putting that what the pic was named as under the pickit config.  In game,  it starts picking up and randomly stashing items that are not the item I just added, but it thinks it is.  

5.  Is there any way to increase the amount of time the character stays at a particular fight, ie travs? My sorc cannot kill them fast enough before it tps.

**Comment by mgleed** [comment]
There is an issue template for a reason. Please discuss these questions in discord.
