### ISSUE TITLE
Botty missing items during pickit

### ISSUE THREAD

**Issue by NeoIsrafil** [aeon0/botty#855]
**Is it really a Bug report?**  Yes, it definitely is, discord didn't really have any answers and i ran a comparison

**Botty Version** .7.3 master branch, problem does not exist with .7.3 compiled file.

**Describe the bug** I caught the botty master branch i was running a path of diablo, trav, nil failing to pick up a grand charm.  I stopped it and ran around the chaos sanctuary, it had missed 2 other grand charms that had dropped in that run as well (one of em was really nice too, lucky I caught it).  it also failed to pick up other items when I tried again and watched it.  it picks up things MOST of the time, but some kind of variance in the mouse clicking is happening making it miss and give up.  I ran the .7.3 compiled version for several hours while eating and listening to a debate, and it didnt seem to miss anything and generally had less trouble.  BOTH are running the same config file, which i configured on the botty master branch and copied into the compile branch folder to update my settings and equalize everything.  SOMETHING is wrong, and I'd rather you guys not have a ton of people complaining when the next compile comes out.  This MAY be a general clicking inaccuracy issue not confined to pickit, as the Lit_sorc pathing in Travencal ALSO has an issue where it misses and clicks to teleport OUTSIDE the walls sometimes.  

**To Reproduce**
...i ran my hammerdin on a path of diablo, nil, trav, in that order.  

**Expected behavior**
Well... I expected it to be able to click on item names at least as well as the compiled version.... lol.  

**Screenshots / Video**
If applicable, add screenshots or even better a short video of the error happening to help explain your problem. Botty often automatically makes screenshots when something goes wrong. Add these also.

**Logs**
Added the relevant part of the info.log in attached file.
 I got a good chunk of the run i referred to where i caught it missing the grand charms.    Note, the LAST failure shown is a full failure, but the other charms were failed BEFORE the inventory was filled by the monarch shield pickup.  

**Additional info**
Not...really sure.  If I had any clue how to help id try fixing it myself, but I havent dug deep enough into the code to figure this thing out yet.  The best i can do is say that i THINK its something to do with the mouseclick accuracy being too low and it literally missing, because that's what it seems like its doing.  Maybe something to do with the window offset math?  I dunno...
[GC failure.txt](https://github.com/aeon0/botty/files/8883529/GC.failure.txt)

**Comment by aeon0** [comment]
Some failures are to be expected. It can have many reasons:
- You killed a mob while walking/pathing and there was never a pickup routine
- The template matching just failed (basically doesnt happen)
- The item seperation failed (happens more often, the more items on the ground, the higher the risk)
- Walking to the item fails, e.g. often happens at trav when item is on another floor (you should teleport there after too many fails though)
- When there is a big lag/delay e.g. because of bad inet connection, you will often missclick because while walking the position of the click changed. Given that you also teleport outside the wals sometimes, this is probably reason Nr 1 for you.

Now you observed quite a high number of this. Imho higher than usual. But not much to go on. Additionally with 0.8 the whole pickit was reworked and changed. So we will most probably not go much deeper into 0.7 optimizations.

**Comment by NeoIsrafil** [comment]
> * When there is a big lag/delay e.g. because of bad inet connection, you will often missclick because while walking the position of the click changed. Given that you also teleport outside the wals sometimes, this is probably reason Nr 1 for you.
> 
> Now you observed quite a high number of this. Imho higher than usual. But not much to go on. Additionally with 0.8 the whole pickit was reworked and changed. So we will most probably not go much deeper into 0.7 optimizations.

This.... but also another user noticed part of the same problem, Ezro posted another issue for it.  We need to be able to tune the time between mouse-move and mouse-click in ms, which would apply to the new 0.8 version too.

We also need a way to introduce an intentional lag between the end of kill and the start of pickit,   or ...maybe a way to run an extra pickit cycle  before going back to traversing.  Different computers and connections are gonna have different needs, and i think that's whats messing us up.  Without doing some REALLY careful math and pulling ping numbers and framerates from the game we would be better off just allowing the user to tune these settings in Params.  I'm not well versed enough in this program yet to DO the modifications necessary without risking breaking something else...or I would just make a branch and do it.  Is anyone willing to take this up?
